services:
  db:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - data:/var/lib/mysql

  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    command: /bin/sh /app/start-server.sh

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  data:
